/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DesktopRouteImport } from './routes/desktop'
import { Route as PageNameRouteImport } from './routes/$pageName'
import { Route as IndexRouteImport } from './routes/index'

const DesktopRoute = DesktopRouteImport.update({
  id: '/desktop',
  path: '/desktop',
  getParentRoute: () => rootRouteImport,
} as any)
const PageNameRoute = PageNameRouteImport.update({
  id: '/$pageName',
  path: '/$pageName',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$pageName': typeof PageNameRoute
  '/desktop': typeof DesktopRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$pageName': typeof PageNameRoute
  '/desktop': typeof DesktopRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$pageName': typeof PageNameRoute
  '/desktop': typeof DesktopRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$pageName' | '/desktop'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$pageName' | '/desktop'
  id: '__root__' | '/' | '/$pageName' | '/desktop'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PageNameRoute: typeof PageNameRoute
  DesktopRoute: typeof DesktopRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/desktop': {
      id: '/desktop'
      path: '/desktop'
      fullPath: '/desktop'
      preLoaderRoute: typeof DesktopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$pageName': {
      id: '/$pageName'
      path: '/$pageName'
      fullPath: '/$pageName'
      preLoaderRoute: typeof PageNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PageNameRoute: PageNameRoute,
  DesktopRoute: DesktopRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
