/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PageNameRouteImport } from './routes/$pageName'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUserRouteImport } from './routes/api/user'
import { Route as ApiStateRouteImport } from './routes/api/state'
import { Route as ApiCurlRouteImport } from './routes/api/curl'

const PageNameRoute = PageNameRouteImport.update({
  id: '/$pageName',
  path: '/$pageName',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserRoute = ApiUserRouteImport.update({
  id: '/api/user',
  path: '/api/user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStateRoute = ApiStateRouteImport.update({
  id: '/api/state',
  path: '/api/state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCurlRoute = ApiCurlRouteImport.update({
  id: '/api/curl',
  path: '/api/curl',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$pageName': typeof PageNameRoute
  '/api/curl': typeof ApiCurlRoute
  '/api/state': typeof ApiStateRoute
  '/api/user': typeof ApiUserRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$pageName': typeof PageNameRoute
  '/api/curl': typeof ApiCurlRoute
  '/api/state': typeof ApiStateRoute
  '/api/user': typeof ApiUserRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$pageName': typeof PageNameRoute
  '/api/curl': typeof ApiCurlRoute
  '/api/state': typeof ApiStateRoute
  '/api/user': typeof ApiUserRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$pageName' | '/api/curl' | '/api/state' | '/api/user'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$pageName' | '/api/curl' | '/api/state' | '/api/user'
  id: '__root__' | '/' | '/$pageName' | '/api/curl' | '/api/state' | '/api/user'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PageNameRoute: typeof PageNameRoute
  ApiCurlRoute: typeof ApiCurlRoute
  ApiStateRoute: typeof ApiStateRoute
  ApiUserRoute: typeof ApiUserRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$pageName': {
      id: '/$pageName'
      path: '/$pageName'
      fullPath: '/$pageName'
      preLoaderRoute: typeof PageNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user': {
      id: '/api/user'
      path: '/api/user'
      fullPath: '/api/user'
      preLoaderRoute: typeof ApiUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/state': {
      id: '/api/state'
      path: '/api/state'
      fullPath: '/api/state'
      preLoaderRoute: typeof ApiStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/curl': {
      id: '/api/curl'
      path: '/api/curl'
      fullPath: '/api/curl'
      preLoaderRoute: typeof ApiCurlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PageNameRoute: PageNameRoute,
  ApiCurlRoute: ApiCurlRoute,
  ApiStateRoute: ApiStateRoute,
  ApiUserRoute: ApiUserRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
